services:
  - type: web
    name: pronghorn-vue-template
    runtime: static
    region: oregon
    branch: main
    repo: https://github.com/pronghorn-red/vue-template.git

    buildCommand: npm install && npm run build
    staticPublishPath: dist

    # Vue Router history mode â†’ always serve index.html
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        statusCode: 200

    autoDeployTrigger: commit
